[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"
  targetPort = 8080

# Redirects all traffic to index.html so React Router works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200